export default {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_VEHICLE_DATA: "GET_VEHICLE_DATA",
  SAVE_USER_SETTINGS: "SAVE_USER_SETTINGS",
  SAVE_USER_DATA: "SAVE_USER_DATA",
  UPDATE_USERNAME: "UPDATE_USERNAME",
  GET_REFRESH_TOKEN: "GET_REFRESH_TOKEN",
  GET_ACCESS_TOKEN: "GET_ACCESS_TOKEN"
};
